version: '2'
services:
  cassandra-seed:
    image: aluxian/cassandra-svc
    container_name: cassandra-seed
    environment:
      - constraint:node==opb
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-seed
    volumes:
      - /openblockchain/cassandra/data:/var/lib/cassandra
    restart: always
  cassandra-01:
    image: aluxian/cassandra-svc
    container_name: cassandra-01
    environment:
      - constraint:node==opb-01
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-01
      - CASSANDRA_SEEDS=cassandra-seed
    depends_on:
      - cassandra-seed
    volumes:
      - /openblockchain/cassandra/data:/var/lib/cassandra
    restart: always
  cassandra-02:
    image: aluxian/cassandra-svc
    container_name: cassandra-02
    environment:
      - constraint:node==opb-02
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-02
      - CASSANDRA_SEEDS=cassandra-seed
    depends_on:
      - cassandra-seed
    volumes:
      - /openblockchain/cassandra/data:/var/lib/cassandra
    restart: always
  bitcoin:
    image: 'aluxian/bitcoin:latest'
    container_name: bitcoin
    command: 'root /usr/bin/bitcoind -conf=/etc/bitcoin.conf -txindex'
    environment:
      - constraint:node==opb-01
      - CONF_RPCALLOWIP=0.0.0.0/0
      - CONF_RPCPASSWORD=pass123
      - CONF_RPCUSER=bitcoinrpc
      - CONF_DBCACHE=2048
      - CONF_RPCTHREADS=8
      - CONF_SERVER=1
    volumes:
      - /openblockchain/bitcoin/data:/bitcoin/data
    restart: always
  scanner-01:
    build: ./scanner
    container_name: scanner-01
    command: './sbttask.sh "run-main org.dyne.danielsan.openblockchain.Driver 1 150000"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - CASSANDRA_HOSTS_NUM=3
      - CASSANDRA_HOST_1=cassandra-seed
      - CASSANDRA_HOST_2=cassandra-01
      - CASSANDRA_HOST_3=cassandra-02
    depends_on:
      - bitcoin
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: always
  scanner-02:
    build: ./scanner
    container_name: scanner-02
    command: './sbttask.sh "run-main org.dyne.danielsan.openblockchain.Driver 150000 250000"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - CASSANDRA_HOSTS_NUM=3
      - CASSANDRA_HOST_1=cassandra-seed
      - CASSANDRA_HOST_2=cassandra-01
      - CASSANDRA_HOST_3=cassandra-02
    depends_on:
      - bitcoin
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: always
  scanner-03:
    build: ./scanner
    container_name: scanner-03
    command: './sbttask.sh "run-main org.dyne.danielsan.openblockchain.Driver 250000 330000"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - CASSANDRA_HOSTS_NUM=3
      - CASSANDRA_HOST_1=cassandra-seed
      - CASSANDRA_HOST_2=cassandra-01
      - CASSANDRA_HOST_3=cassandra-02
    depends_on:
      - bitcoin
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: always
  scanner-04:
    build: ./scanner
    container_name: scanner-04
    command: './sbttask.sh "run-main org.dyne.danielsan.openblockchain.Driver 330000 380000"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - CASSANDRA_HOSTS_NUM=3
      - CASSANDRA_HOST_1=cassandra-seed
      - CASSANDRA_HOST_2=cassandra-01
      - CASSANDRA_HOST_3=cassandra-02
    depends_on:
      - bitcoin
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: always
  scanner-05:
    build: ./scanner
    container_name: scanner-05
    command: './sbttask.sh "run-main org.dyne.danielsan.openblockchain.Driver 380000"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - CASSANDRA_HOSTS_NUM=3
      - CASSANDRA_HOST_1=cassandra-seed
      - CASSANDRA_HOST_2=cassandra-01
      - CASSANDRA_HOST_3=cassandra-02
    depends_on:
      - bitcoin
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: always
  api:
    build: ./api
    container_name: api
    command: './sbttask.sh "~;jetty:stop;jetty:start"'
    environment:
      - CASSANDRA_HOSTS_NUM=3
      - CASSANDRA_HOST_1=cassandra-seed
      - CASSANDRA_HOST_2=cassandra-01
      - CASSANDRA_HOST_3=cassandra-02
    depends_on:
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/api/.ivy2:/root/.ivy2
    restart: always
  frontend:
    build: ./frontend
    container_name: frontend
    command: 'npm run start-prod'
    environment:
      - APIHOST=api
      - APIPORT=8080
    depends_on:
      - api
    restart: always
  spark-submit:
    build: ./spark
    container_name: spark-submit
    command: './run_all_vizgen_cron.sh'
    environment:
      - OBC_SPARK_MASTER=spark://spark-master:7077
      - CASSANDRA_HOSTS_NUM=3
      - CASSANDRA_HOST_1=cassandra-seed
      - CASSANDRA_HOST_2=cassandra-01
      - CASSANDRA_HOST_3=cassandra-02
    ports:
      - '4040:4040'
      - '4041:4041'
      - '4042:4042'
    depends_on:
      - spark-master
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/spark-submit/.ivy2:/root/.ivy2
    restart: always
  spark-master:
    image: aluxian/hadoop-spark-master
    container_name: spark-master
    environment:
      - constraint:node==opb
    ports:
      - '8080:8080'
    restart: always
  spark-worker-01:
    image: aluxian/hadoop-spark-worker
    container_name: spark-worker-01
    environment:
      - constraint:node==opb-01
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_PUBLIC_DNS=opb-01
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    restart: always
  spark-worker-02:
    image: aluxian/hadoop-spark-worker
    container_name: spark-worker-02
    environment:
      - constraint:node==opb-02
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_PUBLIC_DNS=opb-02
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    restart: always
networks:
  default:
    external:
      name: opbnet
