version: '2'
services:
  cassandra-seed:
    image: aluxian/cassandra-svc
    environment:
      - constraint:node==opb
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-seed
    volumes:
      - /openblockchain/cassandra/data:/var/lib/cassandra
    restart: always
  cassandra-01:
    image: aluxian/cassandra-svc
    environment:
      - constraint:node==opb-01
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-01
      - CASSANDRA_SEEDS=cassandra-seed
    depends_on:
      - cassandra-seed
    volumes:
      - /openblockchain/cassandra/data:/var/lib/cassandra
    restart: always
  cassandra-02:
    image: aluxian/cassandra-svc
    environment:
      - constraint:node==opb-02
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-02
      - CASSANDRA_SEEDS=cassandra-seed
    depends_on:
      - cassandra-seed
    volumes:
      - /openblockchain/cassandra/data:/var/lib/cassandra
    restart: always
  bitcoin:
    image: 'aluxian/bitcoin:latest'
    command: 'root /usr/bin/bitcoind -conf=/etc/bitcoin.conf -txindex'
    environment:
      - constraint:node==opb-01
      - CONF_RPCALLOWIP=0.0.0.0/0
      - CONF_RPCPASSWORD=pass123
      - CONF_RPCUSER=bitcoinrpc
      - CONF_DBCACHE=2048
      - CONF_RPCTHREADS=8
      - CONF_SERVER=1
    volumes:
      - /openblockchain/bitcoin/data:/bitcoin/data
    restart: always
  scanner-01:
    build: ./scanner
    command: './sbttask.sh "run-main org.dyne.danielsan.openblockchain.Driver 1 100000"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - CASSANDRA_HOST=cassandra-seed
    depends_on:
      - bitcoin
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: always
  scanner-02:
    build: ./scanner
    command: './sbttask.sh "run-main org.dyne.danielsan.openblockchain.Driver 330000 400000"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - CASSANDRA_HOST=cassandra-seed
    depends_on:
      - bitcoin
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: always
  api:
    build: ./api
    command: './sbttask.sh "~;jetty:stop;jetty:start"'
    environment:
      - CASSANDRA_HOST=cassandra-seed
    depends_on:
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/api/.ivy2:/root/.ivy2
    restart: always
  frontend:
    build: ./frontend
    command: 'npm run start-prod'
    environment:
      - APIHOST=api
      - APIPORT=8080
    depends_on:
      - api
    restart: always
  spark-submit:
    build: ./spark
    command: './run_all_vizgen_cron.sh'
    environment:
      - CASSANDRA_HOST=cassandra-seed
      - OBC_SPARK_MASTER=spark://spark-master:7077
    ports:
      - '4040:4040'
      - '4041:4041'
      - '4042:4042'
    depends_on:
      - spark-master
      - cassandra-seed
      - cassandra-01
      - cassandra-02
    volumes:
      - /openblockchain/spark-submit/.ivy2:/root/.ivy2
    restart: always
  spark-master:
    image: aluxian/hadoop-spark-master
    environment:
      - constraint:node==opb
    ports:
      - '8080:8080'
    restart: always
  spark-worker-01:
    image: aluxian/hadoop-spark-worker
    environment:
      - constraint:node==opb-01
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_PUBLIC_DNS=opb-01
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    restart: always
  spark-worker-02:
    image: aluxian/hadoop-spark-worker
    environment:
      - constraint:node==opb-02
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_PUBLIC_DNS=opb-02
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    restart: always
networks:
  default:
    external:
      name: opbnet
